start-qemu.sh: Support Ubuntu
intel/tdx-tools pull request #123
Opened 2022-06-29 03:35 UTC by ruomengh

Adjust start-qemu.sh so that both CentOS Stream and Ubuntu are supported
Signed-off-by: Hao, Ruomeng <ruomeng.hao@intel.com>

2022-06-29 15:59 UTC, jurobystricky commented on start-qemu.sh
I think we should use something like:
<pre>
if [[ ! -f ${QEMU_EXEC} ]]; then
   error "Please install QEMU which supports TDX."
fi
</pre>

2022-06-30 00:50 UTC, ruomengh commented on start-qemu.sh
Juro, thanks for the comments. Updated.

2022-06-30 01:32 UTC, kenplusplus requested changes

2022-06-30 01:32 UTC, kenplusplus commented on start-qemu.sh
> +KERNEL_CMD_NON_TD="root=${ROOT_PARTITION} console=hvc0"
The logic is incorrect here, please see https://github.com/intel/tdx-tools/blob/a8067f274ae2e07fd7ba1fa381ad4beaa1d630c7/start-qemu.sh#L179

2022-06-30 08:37 UTC, jialeif commented on start-qemu.sh
> +# - Legacy VM: non-TDX VM boot with legacy(non-EFI) SEABIOS at /usr/share/qemu-kvm/bios.bin (CentOS Stream) at /usr/share/qemu/bios-microvm.bin (Ubuntu)
/usr/share/seabios/bios.bin

2022-06-30 08:37 UTC, jialeif commented on start-qemu.sh
> -# 2. Create TDX guest image with
why not keep the prerequisite 1

2022-06-30 17:53 UTC, clsulliv commented
LGTM other than the small issues Jialei pointed out.

2022-07-01 01:28 UTC, ruomengh commented on start-qemu.sh
> -# 2. Create TDX guest image with
It's not appropriate to expose the platform information here. Deleted it as required.

2022-07-01 01:29 UTC, ruomengh commented
@kenplusplus @jurobystricky  @jialeif  Thank you for the review comments. I believe all the comments have been addressed. Would you please review it again?

2022-07-01 01:40 UTC, jialeif commented on start-qemu.sh
> -# 2. Create TDX guest image with
Just need to remove the platform info, how about keep others

2022-07-01 01:40 UTC, kenplusplus approved these changes
LGTM

2022-07-01 02:04 UTC, ruomengh commented on start-qemu.sh
> +# - Legacy VM: non-TDX VM boot with legacy(non-EFI) SEABIOS at /usr/share/qemu-kvm/bios.bin (CentOS Stream) at /usr/share/qemu/bios-microvm.bin (Ubuntu)
Updated

2022-07-01 02:05 UTC, ruomengh commented on start-qemu.sh
> +KERNEL_CMD_NON_TD="root=${ROOT_PARTITION} console=hvc0"
Updated

2022-07-01 02:10 UTC, ruomengh commented on start-qemu.sh
> +# - Legacy VM: non-TDX VM boot with legacy(non-EFI) SEABIOS at /usr/share/qemu-kvm/bios.bin (CentOS Stream) at /usr/share/seabios/bios.bin (Ubuntu)
Updated.

2022-07-01 02:12 UTC, jialeif approved these changes
LGTM

2022-07-01 02:31 UTC, merged