Add guest image tool
intel/tdx-tools pull request #14
Opened 2022-01-15 12:50 UTC by jialeif

2022-01-17 03:56 UTC, kenplusplus requested changes

2022-01-17 03:56 UTC, kenplusplus commented on build/centos-stream-8/guest-image/config/grub
> +GRUB_CMDLINE_LINUX="root=/dev/vda3 rw console=tty0 net.ifnames.prefix=net ipv6.disable=1 quiet systemd.show_status=yes crashkernel=auto console=ttyS0,115200"
Please also add console=hvc0, since in TDX mode, the ttyS0 was disabled by TDX's device filter for security consideration.

2022-01-17 03:56 UTC, kenplusplus commented on build/centos-stream-8/guest-image/create-efi-img.sh
> +    wget ${MIRROR}/${ISO}
Need double quote? Have you tested with shellcheck utility?

2022-01-17 03:56 UTC, kenplusplus commented on build/centos-stream-8/guest-image/install-tdx-stack.sh
> +REPO_DIR=../repo/guest/
Not good to use "../", because if others running script in other directory like "/", then the "../" is incorrect. Please use "$(dirname "$0")" to get the directory path for the script file, then use relative path to that path.

2022-01-17 03:56 UTC, kenplusplus commented on build/centos-stream-8/guest-image/install-tdx-stack.sh
> +ARGS+=" --copy-in config/srv_guest.repo:/etc/yum.repos.d/"
"config/srv_guest" is relative path, if someone run this script at other directory, then it is incorrect. Use absolute path?

2022-01-17 03:56 UTC, kenplusplus commented on build/centos-stream-8/guest-image/kickstart/base.ks
> +#%end
why remove %end? if really unnecessary, please remove it complete without "comment out".

2022-01-18 02:02 UTC, kenplusplus commented on build/centos-stream-8/guest-image/config/grub
> +GRUB_CMDLINE_LINUX="root=/dev/vda3 rw console=hvc0 net.ifnames.prefix=net ipv6.disable=1 quiet systemd.show_status=yes"
Beyond the serial output like hvc0, ttyS0, do we also need keep console=tty0 for virsh console?

2022-01-18 11:50 UTC, jialeif commented on build/centos-stream-8/guest-image/config/grub
> +GRUB_CMDLINE_LINUX="root=/dev/vda3 rw console=hvc0 net.ifnames.prefix=net ipv6.disable=1 quiet systemd.show_status=yes"
virsh console works with hvc0.  kernel boot log can be displayed but grub menu disappeared

2022-01-18 14:50 UTC, kenplusplus approved these changes

2022-01-18 14:51 UTC, merged