SDL: moddify issues by shellcheck snyk
intel/tdx-tools pull request #183
Opened 2022-11-14 10:34 UTC by tenderbulk

2022-11-14 10:55 UTC, kenplusplus requested changes

2022-11-14 10:55 UTC, kenplusplus commented on build/ubuntu-22.04/intel-mvp-tdx-guest-grub2/build.sh
> +    cd "${CURR_DIR}" || exit
why the operation of 'cd "$CURR_DIR"' could be fail?

2022-11-14 10:55 UTC, kenplusplus commented on build/ubuntu-22.04/intel-mvp-tdx-guest-grub2/build.sh
> +        cd "${PACKAGE}-${UPSTREAM_VERSION}" || exit
Why need exit here?

2022-11-14 10:55 UTC, kenplusplus commented on build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
> +        git config user.email "${USER:-tdx-builder}"@"$HOSTNAME"
please change ""@"" to "xxx @xxx"

2022-11-14 10:55 UTC, kenplusplus commented on build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
> +    cp "${CURR_DIR}"/debian/ "${SOURCE_DIR}" -fr
change to "${CURR_DIR}/debian/ ${SOURCE_DIR}"

2022-11-15 01:52 UTC, ruomengh reviewed
I would suggest to add a clear description on why the changes are needed.
For example: 
1. shell check scan issue *** 
2. fix method ***

2022-11-15 03:09 UTC, tenderbulk commented on build/ubuntu-22.04/intel-mvp-tdx-guest-grub2/build.sh
> +        cd "${PACKAGE}-${UPSTREAM_VERSION}" || exit
shell check scan suggests adding "|| exit"

2022-11-15 03:10 UTC, tenderbulk commented on build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
> +        git config user.email "${USER:-tdx-builder}"@"$HOSTNAME"
OK

2022-11-15 03:10 UTC, tenderbulk commented on build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
> +    cp "${CURR_DIR}"/debian/ "${SOURCE_DIR}" -fr
OK

2022-11-15 03:13 UTC, tenderbulk commented on build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
> +    cp "${CURR_DIR}"/debian/ "${SOURCE_DIR}" -fr
seems this  copies directory : ${CURR_DIR}"/debian/    to    Dir : "${SOURCE_DIR}"

2022-11-15 06:43 UTC, kenplusplus commented on build/ubuntu-22.04/intel-mvp-tdx-guest-grub2/build.sh
> +        cd "${PACKAGE}-${UPSTREAM_VERSION}" || exit
Ok, I found it is related to SC2164 https://www.shellcheck.net/wiki/SC2164

2022-11-23 13:39 UTC, closed without merging