Add function for RTMR write
intel/tdx-tools pull request #242
Opened 2023-03-01 07:22 UTC by Ruoyu-y

* Add extra function extend_rtmr to perform rtmr write

2023-03-01 07:35 UTC, Ruoyu-y commented
@kenplusplus Here adds the function for rtmr extend. Please check. Rest of the test cases will be committed to stack-test as another PR.

2023-03-05 12:54 UTC, kenplusplus reviewed
Sound like we need design an actor like https://github.com/intel/tdx-tools/blob/7d80572f1952c23f4c55ab2dea8e5b0231b5d197/attestation/pytdxmeasure/pytdxmeasure/actor.py#L22 to allow user to run it via command line

2023-03-05 12:55 UTC, kenplusplus requested changes

2023-03-05 12:55 UTC, kenplusplus commented on attestation/pytdxmeasure/pytdxmeasure/rtmr.py
> +    def extend_rtmr(raw_extend_data, extend_rtmr_register):
Let user to provide the index of rtmr, instead of hard code 3.

2023-03-05 12:56 UTC, kenplusplus commented
could you please rebase your branch with latest main, since https://github.com/intel/tdx-tools/commit/63c33b593b8669003667af9d7e8d755b8ff6378c will help to fix the issue of github action.

2023-03-06 01:14 UTC, Ruoyu-y commented on attestation/pytdxmeasure/pytdxmeasure/rtmr.py
> +    def extend_rtmr(raw_extend_data, extend_rtmr_register):
> Sound like we need design an actor like
> 
> https://github.com/intel/tdx-tools/blob/7d80572f1952c23f4c55ab2dea8e5b0231b5d197/attestation/pytdxmeasure/pytdxmeasure/actor.py#L22
> 
> to allow user to run it via command line

Sure. I will do that

2023-03-06 01:14 UTC, Ruoyu-y commented on attestation/pytdxmeasure/pytdxmeasure/rtmr.py
> +    def extend_rtmr(raw_extend_data, extend_rtmr_register):
I think currently the variable 'extend_rtmr_register' will give options to user on which index they would like to use. Let me change the variable name to 'extend_rtmr_index' to clarify that.

2023-03-06 01:14 UTC, Ruoyu-y commented
> Sound like we need design an actor like
> 
> https://github.com/intel/tdx-tools/blob/7d80572f1952c23f4c55ab2dea8e5b0231b5d197/attestation/pytdxmeasure/pytdxmeasure/actor.py#L22
> 
> to allow user to run it via command line

Sure.

2023-03-06 15:34 UTC, kenplusplus approved these changes
LGTM

2023-03-06 15:37 UTC, kenplusplus commented
https://github.com/intel/tdx-tools/actions/runs/4343937104/jobs/7589452040#step:6:101 pylint issue

2023-03-07 02:03 UTC, kenplusplus commented on attestation/pytdxmeasure/pytdxmeasure/rtmr.py
> +    def extend_rtmr(raw_extend_data, extend_rtmr_register):
ok.. my bad, not realize it...

2023-03-07 02:04 UTC, kenplusplus approved these changes
LGTM

2023-03-07 02:05 UTC, merged