feature: refactor & update tdreport
intel/tdx-tools pull request #244
Opened 2023-03-02 03:26 UTC by HaokunX-intel

Refactor function TdReport.get_td_report
* Refactor struct tdx_report_req
* Refactor /dev/tdx_guest Operator TDX_CMD_GET_REPORT0

Update tdreport structure
* Append new field tee_tcb_info.tee_tcb_svn2: offset 128 bytes and size 16 bytes
* Append new field tdinfo.servtd_hash: offset 400 bytes and size 48 bytes

Pending
* The field mrservicetd need more knowledge

2023-03-05 12:47 UTC, kenplusplus requested changes

2023-03-05 12:47 UTC, kenplusplus commented on attestation/pytdxmeasure/pytdxmeasure/utility.py
> +    if major < 5 and minor < 19 :
I think it is not a good idea to use kernel version, because customer will backport these patches to their kernel in different kernel version. We should not use hard code kernel version. Instead, we can use device node name.

2023-03-05 12:49 UTC, kenplusplus commented
could you please rebase your branch with latest main, since https://github.com/intel/tdx-tools/commit/63c33b593b8669003667af9d7e8d755b8ff6378c will help to fix the issue of github action.

2023-03-05 13:01 UTC, HaokunX-intel commented on attestation/pytdxmeasure/pytdxmeasure/utility.py
> +    if major < 5 and minor < 19 :
Sure. It is better to use device node name.

2023-03-07 05:29 UTC, jialeif requested changes

2023-03-07 05:29 UTC, jialeif commented on attestation/pytdxmeasure/pytdxmeasure/utility.py
> +# defined in https://github.com/intel-innersource/os.linux.cloud.mvp.kernel-dev/blob/
Remove internal links

2023-03-07 06:08 UTC, HaokunX-intel commented on attestation/pytdxmeasure/pytdxmeasure/utility.py
> +        # https://github.com/intel-innersource/os.linux.cloud.mvp.kernel-dev/blob/
Has been removed.

2023-03-07 06:09 UTC, HaokunX-intel commented on attestation/pytdxmeasure/pytdxmeasure/utility.py
> +# defined in https://github.com/intel-innersource/os.linux.cloud.mvp.kernel-dev/blob/
Has been removed.

2023-03-07 07:38 UTC, kenplusplus approved these changes
LGTM

2023-03-07 12:26 UTC, merged