Initial td-migration document and test scripts
intel/tdx-tools pull request #261
Opened 2023-03-23 13:39 UTC by LeiZhou-97

1. Add the td-migration doc for customers who could follow the single or cross host td-migration test steps to verify its basic function
2. Develop some td-migration required test scripts to simplify its usage.

Signed-off-by: Zhou, Lei <lei.zhou@intel.com>

2023-03-23 13:53 UTC, kenplusplus commented
@ruomengh  @dongx1x  how about put the tools to utils directory?

2023-03-24 01:39 UTC, ruomengh requested changes

2023-03-24 01:39 UTC, ruomengh commented on td-migration/README.md
> +This step has a little different with the single host live migration.
Typo: different -> difference

2023-03-24 01:39 UTC, ruomengh commented on td-migration/README.md
> +This feature is to meet the CSP who may want to relocate/migrate an executing Trust Domain (TD) from a source Trust Domain Extension (TDX) platform to a destination TDX platform in the cloud environm
It's better to be clear on which version/tag should be used for TDX 1.5 - the kernel version  (v6.2) and corresponding tag (2023ww15)

2023-03-24 03:49 UTC, LeiZhou-97 commented
> @ruomengh @dongx1x how about put the tools to utils directory?

Updated, "td-migration" has move to utils dir.

2023-03-24 03:54 UTC, LeiZhou-97 commented
@ruomengh  README has updated based on your advice. Pls. review it again.

2023-03-27 05:28 UTC, ruomengh approved these changes
LGTM

2023-03-27 05:29 UTC, merged