doc: update developer_guide.md
intel/tdx-tools pull request #284
Opened 2023-04-20 07:56 UTC by jialeif

Update to kernel v6.2, qemu v7.2.0 and edk2-stable202302.

2023-04-21 08:14 UTC, ruomengh requested changes

2023-04-21 08:14 UTC, ruomengh commented on doc/developer_guide.md
> +`
Extra ` needs to be removed

2023-04-21 08:27 UTC, jialeif commented on doc/developer_guide.md
> +`
Thanks!

2023-04-26 10:34 UTC, kenplusplus approved these changes
LGTM

2023-04-28 00:14 UTC, ruomengh requested changes

2023-04-28 00:14 UTC, ruomengh commented on doc/developer_guide.md
> +   $ wget https://github.com/intel/tdx-tools/blob/main/build/common/patches-tdx-kernel-MVP-KERNEL-6.2-v1.8.tar.z
tar.z -> tar.gz?

2023-04-28 06:03 UTC, jialeif commented on doc/developer_guide.md
> +   $ wget https://github.com/intel/tdx-tools/blob/main/build/common/patches-tdx-kernel-MVP-KERNEL-6.2-v1.8.tar.z
Thank you!

2023-04-28 08:29 UTC, ruomengh approved these changes
LGTM

2023-04-28 09:49 UTC, merged