attestation/pytdxmeasure: parse module version
intel/tdx-tools pull request #294
Opened 2023-04-27 06:46 UTC by HaokunX-intel

parse and return the valid ModuleVersion

2023-04-27 12:48 UTC, kenplusplus requested changes

2023-04-27 12:48 UTC, kenplusplus commented on attestation/pytdxmeasure/pytdxmeasure/utility.py
> +class ModuleVersion():
do not need ()

2023-04-27 12:48 UTC, kenplusplus commented on attestation/pytdxmeasure/pytdxmeasure/tdreport.py
> +    def try_get_module_version(self):
I dislike this function, look wierd design and confuse with below ModuleVersion class.

2023-05-04 01:03 UTC, HaokunX-intel commented on attestation/pytdxmeasure/pytdxmeasure/utility.py
> +class ModuleVersion():
Sure.

2023-05-04 01:20 UTC, HaokunX-intel commented on attestation/pytdxmeasure/pytdxmeasure/tdreport.py
> +    def try_get_module_version(self):
Sure. It looks a little confusing to share the same function name. The function here is redundant, can be erased.

2023-05-04 02:44 UTC, kenplusplus approved these changes
LGTM

2023-05-05 08:55 UTC, merged