build/ubuntu: improve build-repo.sh for incremental builds
intel/tdx-tools pull request #314
Opened 2023-05-25 05:57 UTC by jialeif

In case of a build failure, re-running build-repo.sh can skip the same and continue the build where it failed.

2023-05-25 05:59 UTC, kenplusplus reviewed
If I want to do a clean build, do I need delete build.done from each directory in 1~2 minutes?

2023-05-25 06:16 UTC, jialeif commented
> If I want to do a clean build, do I need delete build.done from each directory in 1~2 minutes?

 In which case do you need to delete all build.done. `git clean -fd` is clean way, it will delete more obj files.

2023-05-25 06:20 UTC, kenplusplus commented
> > If I want to do a clean build, do I need delete build.done from each directory in 1~2 minutes?
> 
> In which case do you need to delete all build.done. `git clean -fd` is clean way, it will delete more obj files.

So if I made some changes, it will be also clean, we should not leverage git to delete build.done.

2023-05-25 06:22 UTC, jialeif commented
> > > If I want to do a clean build, do I need delete build.done from each directory in 1~2 minutes?
> > 
> > 
> > In which case do you need to delete all build.done. `git clean -fd` is clean way, it will delete more obj files.
> 
> So if I made some changes, it will be also clean, we should not leverage git to delete build.done.

Yes, this is one case, we need delete the build.done in the modified components.

2023-05-25 06:24 UTC, kenplusplus requested changes
So please provides an easier way to cleanup build.done

2023-05-25 06:29 UTC, jialeif commented
> So please provides an easier way to cleanup build.done

In the case of modify only one component, it doesn't make sense to clean all build.done.

2023-05-25 06:31 UTC, kenplusplus commented
> > So please provides an easier way to cleanup build.done
> 
> In the case of modify only one component, it doesn't make sense to clean all build.done.

the requirement is to provide an approach to clean all build.done. I am not argue make sure or not, please do it now

2023-05-25 06:37 UTC, HaokunX-intel commented
The build caches can be placed in one place, such as the directory where the `build/ubuntu-22.04/build-repo.sh` resides and is named by `build/ubuntu-22.04/build-cache`. `touch` a flag file for each component with different name, such as `build/ubuntu-22.04/build-cache/libvirt.done` and `build/ubuntu-22.04/build-cache/qemu.done`. If all building pass, we can delete the directory `build-cache`.

2023-05-25 06:38 UTC, kenplusplus commented
> The build caches can be placed in one place, such as the directory where the `build/ubuntu-22.04/build-repo.sh` resides and is named by `build/ubuntu-22.04/build-cache`. `touch` a flag file for each component with different name, such as `build/ubuntu-22.04/build-cache/libvirt.done` and `build/ubuntu-22.04/build-cache/qemu.done`. If all building pass, we can delete the directory `build-cache`.

This is very nice design and idea! Thanks Haokun!

2023-05-25 07:10 UTC, jialeif commented
> > The build caches can be placed in one place, such as the directory where the `build/ubuntu-22.04/build-repo.sh` resides and is named by `build/ubuntu-22.04/build-cache`. `touch` a flag file for each component with different name, such as `build/ubuntu-22.04/build-cache/libvirt.done` and `build/ubuntu-22.04/build-cache/qemu.done`. If all building pass, we can delete the directory `build-cache`.
> 
> This is very nice design and idea! Thanks Haokun!

Nice! How about build-status?

2023-05-26 02:21 UTC, intelzhongjie commented
Here are my thoughts FYI. Point out if my understanding is wrong:
1. It may be better that adding an option for build-repo.sh so caller can decide if it's "incremental build" or "clean build from scratch"
2. Please consider this case: first, build-repo.sh start, then one of the "sub-build" failed but others succeeded, just at this time, someone's commit to one of the repos got merged which built successfully just in previous attempt, then is your current logic able to handle this case correctly as required?

2023-05-26 02:39 UTC, jialeif commented
> Here are my thoughts FYI. Point out if my understanding is wrong:
> 
> 1. It may be better that adding an option for build-repo.sh so caller can decide if it's "incremental build" or "clean build from scratch". Is there any existing "cache" mechanism of make/compile used by our case?
> 2. Please consider this case: first, build-repo.sh start, then one of the "sub-build" failed but others succeeded, just at this time, someone's commit to one of the repos got merged which built successfully just in previous attempt, then is your current logic able to handle this case correctly as required?

Thanks all! Let me update it.

2023-05-26 03:06 UTC, jialeif commented
@kenplusplus @HaokunX-intel @intelzhongjie  Please review the changes.

2023-05-26 03:11 UTC, intelzhongjie commented on build/ubuntu-22.04/build-repo.sh
> +build_check( ) {
Just remove this unnecessary space here

2023-05-26 03:22 UTC, intelzhongjie commented on build/ubuntu-22.04/build-repo.sh
> +    if [[ "$1" == clean-build ]]; then
So the current logic implies that the default option is "incremental", correct?

2023-05-26 03:22 UTC, intelzhongjie commented on build/ubuntu-22.04/build-repo.sh
> +build_check $1
Then please carefully consider the usage of this $1 in the caller and the default behavior when $1 is none/empty.

2023-05-26 03:49 UTC, jialeif commented on build/ubuntu-22.04/build-repo.sh
> +build_check( ) {
updated

2023-05-26 03:50 UTC, jialeif commented on build/ubuntu-22.04/build-repo.sh
> +build_check $1
default for incremental build

2023-05-26 04:03 UTC, intelzhongjie approved these changes
ship it!

2023-05-26 07:56 UTC, kenplusplus approved these changes
LGTM

2023-05-26 07:56 UTC, kenplusplus approved these changes
LGTM

2023-05-26 07:56 UTC, kenplusplus approved these changes
LGTM

2023-05-26 07:56 UTC, kenplusplus approved these changes
LGTM

2023-05-26 07:57 UTC, merged