build/ubuntu22.04/guest-image: new guest image creation tool
intel/tdx-tools pull request #347
Opened 2023-06-21 09:55 UTC by kenplusplus

1. Still create the TDX image based on the official https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
2. Allow the customization on disk image size
3. Allow the customization on cloud-init’s configuration
4. Install measured boot packages
5. Install pytdxmeasure tool by default

2023-06-21 10:01 UTC, kenplusplus commented
@hairongchen let add udev rule for "/dev/tdx-guest" also.

2023-06-21 10:43 UTC, jialeif approved these changes
LGTM.
Thanks Ken for the new design for ubuntu image tool.
Sound like it brings few usage changes in qemu and libvirt to launch ciiso.iso. Shall we make the changes accordingly.

2023-06-21 10:48 UTC, jialeif commented on build/ubuntu-22.04/guest-image/create-ubuntu-image.sh
> +install_tdx_guest_rpms() {
better to use generic function naming over  instead of *_rpm

2023-06-21 13:09 UTC, kenplusplus commented
> LGTM. Thanks Ken for the new design for ubuntu image tool. Sound like it brings few usage changes in qemu and libvirt to launch ciiso.iso. Shall we make the changes accordingly.

ciiso.iso is created from cloud-init script see https://github.com/kenplusplus/tdx-tools/blob/9c5c40aa7edf34ed0e91d20c7b2428744110b31d/build/ubuntu-22.04/guest-image/create-ubuntu-image.sh#L177 
it like kickstart.ks file.

2023-06-21 13:14 UTC, kenplusplus commented on build/ubuntu-22.04/guest-image/create-ubuntu-image.sh
> +install_tdx_guest_rpms() {
how about packages? see https://github.com/intel/tdx-tools/compare/9c5c40aa7edf34ed0e91d20c7b2428744110b31d..cb00d372faef523e02d6878b65ac223eb836aa7d

2023-06-21 20:12 UTC, matti commented
This needs more documentation / checking on the pre-requisites.

Eg. if I have a just installed bare metal host, what do I need to do before running this?

2023-06-21 20:13 UTC, matti requested changes

2023-06-21 20:13 UTC, matti commented on build/ubuntu-22.04/guest-image/create-ubuntu-image.sh
> +config-cloud-init() {
inconsistent naming with dashes instead of underscores

2023-06-21 20:13 UTC, matti commented on build/ubuntu-22.04/guest-image/create-ubuntu-image.sh
> +
check_prerequisites here that ensures that the host is capable of running a TDX guest

2023-06-21 21:12 UTC, kenplusplus commented
> This needs more documentation / checking on the pre-requisites.
> 
> Eg. if I have a just installed bare metal host, what do I need to do before running this?

This tool is not running on TDX capable system, this tool is only to create guest image, which can running on any Linux system.

2023-06-21 21:29 UTC, kenplusplus commented on build/ubuntu-22.04/guest-image/create-ubuntu-image.sh
> +config-cloud-init() {
nice catch, fixed at https://github.com/intel/tdx-tools/pull/347/commits/42bb30d11e2e3966c0ee1801391772f67ae0ba11

2023-06-21 22:15 UTC, kenplusplus commented
> > @hairongchen let add udev rule for "/dev/tdx-guest" also.
> 
> current rules used in CCNP: /etc/udev/rules.d/90-tdx.rules SUBSYSTEM=="misc",KERNEL=="tdx-guest",MODE="0666"

Add at commit https://github.com/intel/tdx-tools/pull/347/commits/269443015411a14476f9e02aba333ca0045f97c1

2023-06-22 04:23 UTC, matti commented
please post /proc/cpuinfo from a succesfull run of this script

2023-06-22 05:27 UTC, kenplusplus commented
> please post /proc/cpuinfo from a succesfull run of this script

I am planning to add this on github action CI, since it can run on any container/VM environment provided by github.

2023-06-22 11:19 UTC, merged