add secure boot guide for tdx
intel/tdx-tools pull request #36
Opened 2022-03-18 09:10 UTC by jialeif

Introdcue the steps to enable secure boot in a td guest.
The guide uses utils/tdvf-key-enroll in this repo.

Signed-off-by: jialeie <jialei.feng@intel.com>

2022-03-23 05:20 UTC, ruomengh reviewed
At "Boot VM" part, for qemu, is it better to point to start-qemu.sh which is also in tdx-tools?
For libvirt, it mentions "xml template" while it doesn't give any xml template

2022-03-23 05:20 UTC, ruomengh commented on doc/secure_boot.md
> ++ Use sbsigntools to sign Shim / Grub / Kernel in the QCOW2 image wiht private keys generated above
typo: wiht->with

2022-03-23 09:33 UTC, jialeif commented on doc/secure_boot.md
> ++ Use sbsigntools to sign Shim / Grub / Kernel in the QCOW2 image wiht private keys generated above
Thanks your comments. I've updated

2022-03-23 13:11 UTC, kenplusplus approved these changes

2022-03-23 19:52 UTC, clsulliv requested changes
Found one small issue.

Sorry for not seeing this sooner.

2022-03-23 19:52 UTC, clsulliv commented on doc/secure_boot.md
> +By Libvirt, please update [xml template](https://github.com/jialeif/tdx-tools/blob/main/doc/tdx_libvirt_grub.xml.template) before boot TD guest.
This sentence is a little confusing. Its also pointing to your fork which I don't think was your intention.

It would be better as:

To boot via libvirt, please update the [xml template](https://github.com/intel/tdx-tools/blob/main/doc/tdx_libvirt_grub.xml.template) as follows before running the usual `virsh` commands.

2022-03-24 05:54 UTC, jialeif commented on doc/secure_boot.md
> +By Libvirt, please update [xml template](https://github.com/jialeif/tdx-tools/blob/main/doc/tdx_libvirt_grub.xml.template) before boot TD guest.
updated. Thanks~

2022-03-24 17:41 UTC, clsulliv commented on doc/secure_boot.md
> +To boot via libvirt, please update the [xml template](https://github.com/jialeif/tdx-tools/blob/main/doc/tdx_libvirt_grub.xml.template) as follows before running the usual virsh commands.
Its still pointing to github.com/jialeif...

2022-03-25 01:47 UTC, jialeif commented on doc/secure_boot.md
> +To boot via libvirt, please update the [xml template](https://github.com/jialeif/tdx-tools/blob/main/doc/tdx_libvirt_grub.xml.template) as follows before running the usual virsh commands.
sorry.. should be fixed now

2022-03-25 02:54 UTC, merged