util/td-migration: Update scripts to support migration advanced features
intel/tdx-tools pull request #374
Opened 2023-06-30 03:39 UTC by ruomengh

1. Pre-binding
2. Post-copy
3. Multi-stream

2023-06-30 05:08 UTC, LeiZhou-97 commented on utils/td-migration/user-td.sh
> +MIG_HASH="d83d9a38c238ef3b7bc207bbea3287a8b37b37e731480a8d240d2a6953086c5ecbdf7ee4c72fec3a3e9d4a87f4f9b4fe"
how about add one more parameter for mig_hash?

mig_hash may different, if use different config.

2023-06-30 05:22 UTC, ruomengh commented on utils/td-migration/user-td.sh
> +MIG_HASH="d83d9a38c238ef3b7bc207bbea3287a8b37b37e731480a8d240d2a6953086c5ecbdf7ee4c72fec3a3e9d4a87f4f9b4fe"
This needs to be enhanced later after more hash is supported. Currently this one is used by default.

2023-06-30 05:28 UTC, LeiZhou-97 approved these changes
LGTM.

2023-07-02 07:19 UTC, kenplusplus requested changes

2023-07-02 07:19 UTC, kenplusplus commented on utils/td-migration/mig-td.sh
> +# QEMU_EXEC="/home/xiaocheng/ws/qemu-bkc/build/qemu-system-x86_64"
Please remove comment-out code.

2023-07-03 02:08 UTC, ruomengh commented
Close the PR and rebase in another PR.

2023-07-03 02:08 UTC, closed without merging