pycloudstack: support to add driver in xml template
intel/tdx-tools pull request #457
Opened 2023-08-18 03:29 UTC by ruomengh

1. Support to add driver in xml template for network perf test
2. Update vtpmtd binary name in vmparam.py

2023-08-19 03:01 UTC, kenplusplus requested changes

2023-08-19 03:01 UTC, kenplusplus commented on utils/pycloudstack/pycloudstack/virtxml.py
> +    def set_driver(self, driver):
set_driver sound a little confusing, what driver?

2023-08-19 03:01 UTC, kenplusplus commented on utils/pycloudstack/pycloudstack/vmparam.py
> +VTPM_PATH = "/usr/share/tdx-vtpm/vtpmtd.bin"
could we split this into a new patch, vtpmtd.bin is belong to driver?

2023-08-21 03:36 UTC, ruomengh commented on utils/pycloudstack/pycloudstack/vmparam.py
> +VTPM_PATH = "/usr/share/tdx-vtpm/vtpmtd.bin"
OK, I'll close this PR and open a new one to separate the changes.

2023-08-21 03:37 UTC, ruomengh commented
Will raise new PRs to separate the changes according to review comment.

2023-08-21 03:37 UTC, closed without merging