Refine guest image tool for Ubuntu22.04
intel/tdx-tools pull request #463
Opened 2023-08-22 08:58 UTC by HaokunX-intel

Refine guest image tool for Ubuntu22.04
* reorg guest&host repo
* support basic guest image
* support testing guest image
* support customization guest image

2023-08-23 07:22 UTC, jialeif commented on build/ubuntu-22.04/README.md
> +./pkg-builder -r intel-mvp-ovmf/build.sh
-r or -s?

2023-08-23 07:22 UTC, jialeif commented on build/ubuntu-22.04/build-repo.sh
> +    _build_repo ./more
Is more/ directory still needed?

2023-08-23 07:22 UTC, jialeif commented on build/ubuntu-22.04/build-repo.sh
> +    pushd intel-mvp-tdx-guest-shim
@ruomengh  will shim and grub be included in next release?

2023-08-23 07:22 UTC, jialeif commented on build/ubuntu-22.04/build-repo.sh
> +    fi
do you want a clean mini-dinstall/ directory via line 116-127?

2023-08-23 07:29 UTC, ruomengh commented on build/ubuntu-22.04/build-repo.sh
> +    pushd intel-mvp-tdx-guest-shim
I don't think we need to build grub and shim for Ubuntu repo anymore. Instead distro grub and shim will be used by users.

2023-08-23 09:11 UTC, HaokunX-intel commented on build/ubuntu-22.04/README.md
> +./pkg-builder -r intel-mvp-ovmf/build.sh
should be -s.

2023-08-23 09:12 UTC, HaokunX-intel commented on build/ubuntu-22.04/build-repo.sh
> +    _build_repo ./more
It can be renamed by "incoming".

2023-08-24 06:56 UTC, jialeif commented on build/ubuntu-22.04/README.md
> +sudo apt -y --allow-downgrades install ./jammy/all/*.deb
Since it changed to include all Debian packages, I don't recommend installing all of them.

2023-08-24 06:56 UTC, jialeif commented on build/ubuntu-22.04/guest-image/README.md
> +4. Specify the `user name`, `password` and `hostname`
username is better

2023-08-24 06:56 UTC, jialeif commented on build/ubuntu-22.04/build-repo.sh
> +    _build_repo ./incoming
conflicts with  line 123  mv $PKG_DIR ./mini-dinstall/incoming

2023-08-28 01:10 UTC, kenplusplus requested changes

2023-08-28 01:10 UTC, kenplusplus commented on build/ubuntu-22.04/pkg-builder
> +            e) USING_EXITING_IMG=true;;
why we need s, e, ? Could we remove it?

2023-08-31 08:31 UTC, jialeif commented on .github/workflows/pr-ubuntu-22.04-ovmf.yml
> +          ./pkg-builder -s intel-mvp-ovmf/build.sh
In your another PR for 1.0 it is "./pkg-builder -c". Please unify the usage.

2023-08-31 08:36 UTC, jialeif commented on build/ubuntu-22.04/README.md
> +on any Linux OS. `./pkg-builder -r <build-script>` will automatically create a
Please unify it, "-r" is the third different usage besides "-c", "-s".

2023-08-31 08:41 UTC, closed without merging