build-repo: move guest kernel packages if they exist
intel/tdx-tools pull request #68
Opened 2022-04-04 17:10 UTC by jialeif

When running build-repo.sh again, e.g. customize qemu and then rebuild repo,
most likely guest kernel packages have already been moved.

Signed-off-by: Feng, Jialei <jialei.feng@intel.com>

2022-04-05 23:29 UTC, clsulliv requested changes

2022-04-05 23:29 UTC, clsulliv commented on build/centos-stream-8/build-repo.sh
> +        if ls repo/"${begin}"/x86_64/"${package}"* >/dev/null 2>&1; then
I'm not really a fan of the syntax of these if statements. Using `ls` should also be avoided if possible.

Perhaps something like this would be better:
```
if [ -f repo/"${begin}"/x86_64/"${package}"* ]; then
...
```

2022-04-06 00:09 UTC, jialeif commented on build/centos-stream-8/build-repo.sh
> +        if ls repo/"${begin}"/x86_64/"${package}"* >/dev/null 2>&1; then
Yes, I also prefer to use the statement you given. But * will match multiple files and will report "[: too many arguments"

2022-04-06 00:11 UTC, clsulliv commented on build/centos-stream-8/build-repo.sh
> +        if ls repo/"${begin}"/x86_64/"${package}"* >/dev/null 2>&1; then
Hmm, you're right. I was only testing with one matched file. I'll think about this a little more.

2022-04-11 18:58 UTC, clsulliv approved these changes
Although I'm not entirely a fan of this syntax, its an improvement and works. We can revisit later if needed.

2022-04-11 18:58 UTC, merged